// <auto-generated />
using DevOpsRealUnitTestWebApi.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevOpsRealUnitTestWebApi.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevOpsRealUnitTestWebApi.Entitys.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Product 1",
                            Price = 10.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Product 2",
                            Price = 20.0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Product 3",
                            Price = 30.0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Product 4",
                            Price = 40.0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Product 5",
                            Price = 50.0
                        },
                        new
                        {
                            Id = 6,
                            Name = "Product 6",
                            Price = 60.0
                        },
                        new
                        {
                            Id = 7,
                            Name = "Product 7",
                            Price = 70.0
                        },
                        new
                        {
                            Id = 8,
                            Name = "Product 8",
                            Price = 80.0
                        },
                        new
                        {
                            Id = 9,
                            Name = "Product 9",
                            Price = 90.0
                        },
                        new
                        {
                            Id = 10,
                            Name = "Product 10",
                            Price = 100.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
